CREATE TABLE telco_churn_raw (
    CustomerID VARCHAR(20) NOT NULL,
    `Count` INT,
    Country VARCHAR(50),
    State VARCHAR(50),
    City VARCHAR(100),
    `Zip Code` INT,
    `Lat Long` VARCHAR(30),
    Latitude DECIMAL(10,6),
    Longitude DECIMAL(10,6),
    Gender VARCHAR(20),
    `Senior Citizen` VARCHAR(10),
    Partner VARCHAR(10),
    Dependents VARCHAR(10),
    `Tenure Months` INT,
    `Phone Service` VARCHAR(20),
    `Multiple Lines` VARCHAR(30),
    `Internet Service` VARCHAR(30),
    `Online Security` VARCHAR(30),
    `Online Backup` VARCHAR(30),
    `Device Protection` VARCHAR(30),
    `Tech Support` VARCHAR(30),
    `Streaming TV` VARCHAR(30),
    `Streaming Movies` VARCHAR(30),
    Contract VARCHAR(30),
    `Paperless Billing` VARCHAR(10),
    `Payment Method` VARCHAR(50),
    `Monthly Charges` DECIMAL(10,2),
    `Total Charges` VARCHAR(30),
    `Churn Label` VARCHAR(10),
    `Churn Value` INT,
    `Churn Score` INT,
    CLTV INT,
    `Churn Reason` VARCHAR(150)
);